//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public long ConProducto { get; set; }
        public Nullable<long> ConModelo { get; set; }
        public Nullable<long> ConMarca { get; set; }
        public Nullable<long> ConCategoria { get; set; }
        public decimal Precio { get; set; }
        public long Stock { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MODELO MODELO { get; set; }
    }
}
