//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.MAESTROes = new HashSet<MAESTRO>();
        }
    
        public long ConUsuario { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Contrasenna { get; set; }
        public Nullable<long> ConRol { get; set; }
        public Nullable<long> ConProvincia { get; set; }
        public Nullable<long> ConCanton { get; set; }
        public string Imagen { get; set; }
    
        public virtual CANTON CANTON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAESTRO> MAESTROes { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
